var namespacecl_1_1uv_1_1leikelen_1_1_module_1_1_general_1_1_gesture_configuration_1_1_properties =
[
    [ "GestureConfiguration", "classcl_1_1uv_1_1leikelen_1_1_module_1_1_general_1_1_gesture_configuration_1_1_properties_1_1_gesture_configuration.html", null ]
];