var namespacecl_1_1uv_1_1leikelen_1_1_a_p_i_1_1_frame_provider_1_1_accelerometer =
[
    [ "AccelerometerFrameArrivedEventArgs", "classcl_1_1uv_1_1leikelen_1_1_a_p_i_1_1_frame_provider_1_1_accelerometer_1_1_accelerometer_frame_arrived_event_args.html", "classcl_1_1uv_1_1leikelen_1_1_a_p_i_1_1_frame_provider_1_1_accelerometer_1_1_accelerometer_frame_arrived_event_args" ],
    [ "IAccelerometerProcessingModule", "interfacecl_1_1uv_1_1leikelen_1_1_a_p_i_1_1_frame_provider_1_1_accelerometer_1_1_i_accelerometer_processing_module.html", "interfacecl_1_1uv_1_1leikelen_1_1_a_p_i_1_1_frame_provider_1_1_accelerometer_1_1_i_accelerometer_processing_module" ]
];